### ISSUE TITLE
Access to the dataset

### ISSUE THREAD

**Issue by BruunoMM** [crowdAI/skip-prediction-challenge-starter-kit#4]
Hello! I was wondering if someone still had access to the dataset. I started a project a couple months in college about this challenge, but as it was in an initial stage I hadn't download the dataset, but now I can't login in CrowdAI and have lost access to the dataset. Could anyone who still have access help me out with that? I would really really appreciate! :(

**Comment by lucianolorenti** [comment]
Hi! The dataset is now located at:

https://www.aicrowd.com/challenges/spotify-sequential-skip-prediction-challenge-old

**Comment by Pravesh001** [comment]
> 
> 
> Hi! The dataset is now located at:
> 
> https://www.aicrowd.com/challenges/spotify-sequential-skip-prediction-challenge-old

Thankyou, but the dataset is not accessible there also. Please help.

**Comment by lucianolorenti** [comment]
I  accessed it from there just a few minutes ago
